/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import jooq.tables.ProjectKeywords

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ProjectKeywordsRecord() : UpdatableRecordImpl<ProjectKeywordsRecord>(ProjectKeywords.PROJECT_KEYWORDS) {

    open var id: Int?
        set(value): Unit = set(0, value)
        get(): Int? = get(0) as Int?

    open var projectId: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var keyword: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<Int?> = super.key() as Record1<Int?>

    /**
     * Create a detached, initialised ProjectKeywordsRecord
     */
    constructor(id: Int? = null, projectId: String? = null, keyword: String? = null): this() {
        this.id = id
        this.projectId = projectId
        this.keyword = keyword
        resetTouchedOnNotNull()
    }
}
