/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import jooq.tables.Teacher

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class TeacherRecord() : UpdatableRecordImpl<TeacherRecord>(Teacher.TEACHER) {

    open var uuid: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var revision: Int?
        set(value): Unit = set(1, value)
        get(): Int? = get(1) as Int?

    open var idempotencyToken: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var firstName: String?
        set(value): Unit = set(3, value)
        get(): String? = get(3) as String?

    open var lastName: String?
        set(value): Unit = set(4, value)
        get(): String? = get(4) as String?

    open var patronymic: String?
        set(value): Unit = set(5, value)
        get(): String? = get(5) as String?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised TeacherRecord
     */
    constructor(uuid: String? = null, revision: Int? = null, idempotencyToken: String? = null, firstName: String? = null, lastName: String? = null, patronymic: String? = null): this() {
        this.uuid = uuid
        this.revision = revision
        this.idempotencyToken = idempotencyToken
        this.firstName = firstName
        this.lastName = lastName
        this.patronymic = patronymic
        resetTouchedOnNotNull()
    }
}
