/*
 * This file is generated by jOOQ.
 */
package jooq.tables.records


import java.time.LocalDate

import jooq.tables.Team

import org.jooq.Record1
import org.jooq.impl.UpdatableRecordImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class TeamRecord() : UpdatableRecordImpl<TeamRecord>(Team.TEAM) {

    open var uuid: String?
        set(value): Unit = set(0, value)
        get(): String? = get(0) as String?

    open var idempotencyToken: String?
        set(value): Unit = set(1, value)
        get(): String? = get(1) as String?

    open var teacher: String?
        set(value): Unit = set(2, value)
        get(): String? = get(2) as String?

    open var organizationDate: LocalDate?
        set(value): Unit = set(3, value)
        get(): LocalDate? = get(3) as LocalDate?

    open var revision: Int?
        set(value): Unit = set(4, value)
        get(): Int? = get(4) as Int?

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    override fun key(): Record1<String?> = super.key() as Record1<String?>

    /**
     * Create a detached, initialised TeamRecord
     */
    constructor(uuid: String? = null, idempotencyToken: String? = null, teacher: String? = null, organizationDate: LocalDate? = null, revision: Int? = null): this() {
        this.uuid = uuid
        this.idempotencyToken = idempotencyToken
        this.teacher = teacher
        this.organizationDate = organizationDate
        this.revision = revision
        resetTouchedOnNotNull()
    }
}
