@file:Suppress("warnings")
/*
 * This file is generated by jOOQ.
 */
package jooq.tables.references


import jooq.tables.Customer
import jooq.tables.Project
import jooq.tables.ProjectKeywords
import jooq.tables.ProjectProgress
import jooq.tables.ProjectRequest
import jooq.tables.ProjectScope
import jooq.tables.Student
import jooq.tables.Teacher
import jooq.tables.Team



/**
 * The table <code>public.customer</code>.
 */
val CUSTOMER: Customer = Customer.CUSTOMER

/**
 * The table <code>public.project</code>.
 */
val PROJECT: Project = Project.PROJECT

/**
 * The table <code>public.project_keywords</code>.
 */
val PROJECT_KEYWORDS: ProjectKeywords = ProjectKeywords.PROJECT_KEYWORDS

/**
 * The table <code>public.project_progress</code>.
 */
val PROJECT_PROGRESS: ProjectProgress = ProjectProgress.PROJECT_PROGRESS

/**
 * The table <code>public.project_request</code>.
 */
val PROJECT_REQUEST: ProjectRequest = ProjectRequest.PROJECT_REQUEST

/**
 * The table <code>public.project_scope</code>.
 */
val PROJECT_SCOPE: ProjectScope = ProjectScope.PROJECT_SCOPE

/**
 * The table <code>public.student</code>.
 */
val STUDENT: Student = Student.STUDENT

/**
 * The table <code>public.teacher</code>.
 */
val TEACHER: Teacher = Teacher.TEACHER

/**
 * The table <code>public.team</code>.
 */
val TEAM: Team = Team.TEAM
