spring:
  application:
    name: showcase-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/showcase
    username: postgres
    password: postgres
