/*
 * This file is generated by jOOQ.
 */
package jooq


import jooq.tables.Project
import jooq.tables.ProjectKeywords
import jooq.tables.ProjectProgress
import jooq.tables.ProjectRequest
import jooq.tables.ProjectScope
import jooq.tables.Student
import jooq.tables.Teacher
import jooq.tables.Team

import kotlin.collections.List

import org.jooq.Catalog
import org.jooq.Table
import org.jooq.impl.DSL
import org.jooq.impl.SchemaImpl


/**
 * standard public schema
 */
@Suppress("warnings")
open class Public : SchemaImpl(DSL.name("public"), DefaultCatalog.DEFAULT_CATALOG, DSL.comment("standard public schema")) {
    companion object {

        /**
         * The reference instance of <code>public</code>
         */
        val PUBLIC: Public = Public()
    }

    /**
     * The table <code>public.project</code>.
     */
    val PROJECT: Project get() = Project.PROJECT

    /**
     * The table <code>public.project_keywords</code>.
     */
    val PROJECT_KEYWORDS: ProjectKeywords get() = ProjectKeywords.PROJECT_KEYWORDS

    /**
     * The table <code>public.project_progress</code>.
     */
    val PROJECT_PROGRESS: ProjectProgress get() = ProjectProgress.PROJECT_PROGRESS

    /**
     * The table <code>public.project_request</code>.
     */
    val PROJECT_REQUEST: ProjectRequest get() = ProjectRequest.PROJECT_REQUEST

    /**
     * The table <code>public.project_scope</code>.
     */
    val PROJECT_SCOPE: ProjectScope get() = ProjectScope.PROJECT_SCOPE

    /**
     * The table <code>public.student</code>.
     */
    val STUDENT: Student get() = Student.STUDENT

    /**
     * The table <code>public.teacher</code>.
     */
    val TEACHER: Teacher get() = Teacher.TEACHER

    /**
     * The table <code>public.team</code>.
     */
    val TEAM: Team get() = Team.TEAM

    override fun getCatalog(): Catalog = DefaultCatalog.DEFAULT_CATALOG

    override fun getTables(): List<Table<*>> = listOf(
        Project.PROJECT,
        ProjectKeywords.PROJECT_KEYWORDS,
        ProjectProgress.PROJECT_PROGRESS,
        ProjectRequest.PROJECT_REQUEST,
        ProjectScope.PROJECT_SCOPE,
        Student.STUDENT,
        Teacher.TEACHER,
        Team.TEAM
    )
}
