/*
 * This file is generated by jOOQ.
 */
package jooq.tables


import java.time.LocalDate

import jooq.Public
import jooq.keys.PROJECT_REQUEST_PKEY
import jooq.keys.PROJECT_REQUEST__PROJECT_REQUEST_PROJECT_ID_FKEY
import jooq.keys.PROJECT_REQUEST__PROJECT_REQUEST_TEAM_ID_FKEY
import jooq.tables.Project.ProjectPath
import jooq.tables.Team.TeamPath
import jooq.tables.records.ProjectRequestRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ProjectRequest(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProjectRequestRecord>?,
    parentPath: InverseForeignKey<out Record, ProjectRequestRecord>?,
    aliased: Table<ProjectRequestRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProjectRequestRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.project_request</code>
         */
        val PROJECT_REQUEST: ProjectRequest = ProjectRequest()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProjectRequestRecord> = ProjectRequestRecord::class.java

    /**
     * The column <code>public.project_request.uuid</code>.
     */
    val UUID: TableField<ProjectRequestRecord, String?> = createField(DSL.name("uuid"), SQLDataType.VARCHAR(255).nullable(false), this, "")

    /**
     * The column <code>public.project_request.project_id</code>.
     */
    val PROJECT_ID: TableField<ProjectRequestRecord, String?> = createField(DSL.name("project_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.project_request.idempotency_token</code>.
     */
    val IDEMPOTENCY_TOKEN: TableField<ProjectRequestRecord, String?> = createField(DSL.name("idempotency_token"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.project_request.team_id</code>.
     */
    val TEAM_ID: TableField<ProjectRequestRecord, String?> = createField(DSL.name("team_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.project_request.date</code>.
     */
    val DATE: TableField<ProjectRequestRecord, LocalDate?> = createField(DSL.name("date"), SQLDataType.LOCALDATE, this, "")

    /**
     * The column <code>public.project_request.context</code>.
     */
    val CONTEXT: TableField<ProjectRequestRecord, String?> = createField(DSL.name("context"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.project_request.request_status</code>.
     */
    val REQUEST_STATUS: TableField<ProjectRequestRecord, String?> = createField(DSL.name("request_status"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<ProjectRequestRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProjectRequestRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProjectRequestRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.project_request</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.project_request</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.project_request</code> table reference
     */
    constructor(): this(DSL.name("project_request"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProjectRequestRecord>?, parentPath: InverseForeignKey<out Record, ProjectRequestRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PROJECT_REQUEST, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ProjectRequestPath : ProjectRequest, Path<ProjectRequestRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProjectRequestRecord>?, parentPath: InverseForeignKey<out Record, ProjectRequestRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ProjectRequestRecord>): super(alias, aliased)
        override fun `as`(alias: String): ProjectRequestPath = ProjectRequestPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ProjectRequestPath = ProjectRequestPath(alias, this)
        override fun `as`(alias: Table<*>): ProjectRequestPath = ProjectRequestPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ProjectRequestRecord> = PROJECT_REQUEST_PKEY
    override fun getReferences(): List<ForeignKey<ProjectRequestRecord, *>> = listOf(PROJECT_REQUEST__PROJECT_REQUEST_PROJECT_ID_FKEY, PROJECT_REQUEST__PROJECT_REQUEST_TEAM_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    fun project(): ProjectPath = project
    val project: ProjectPath by lazy { ProjectPath(this, PROJECT_REQUEST__PROJECT_REQUEST_PROJECT_ID_FKEY, null) }

    /**
     * Get the implicit join path to the <code>public.team</code> table.
     */
    fun team(): TeamPath = team
    val team: TeamPath by lazy { TeamPath(this, PROJECT_REQUEST__PROJECT_REQUEST_TEAM_ID_FKEY, null) }
    override fun `as`(alias: String): ProjectRequest = ProjectRequest(DSL.name(alias), this)
    override fun `as`(alias: Name): ProjectRequest = ProjectRequest(alias, this)
    override fun `as`(alias: Table<*>): ProjectRequest = ProjectRequest(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ProjectRequest = ProjectRequest(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ProjectRequest = ProjectRequest(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ProjectRequest = ProjectRequest(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ProjectRequest = ProjectRequest(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ProjectRequest = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ProjectRequest = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ProjectRequest = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ProjectRequest = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ProjectRequest = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ProjectRequest = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ProjectRequest = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ProjectRequest = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ProjectRequest = where(DSL.notExists(select))
}
