/*
 * This file is generated by jOOQ.
 */
package jooq.tables


import jooq.Public
import jooq.keys.PROJECT_KEYWORDS_PKEY
import jooq.keys.PROJECT_KEYWORDS__PROJECT_KEYWORDS_PROJECT_ID_FKEY
import jooq.tables.Project.ProjectPath
import jooq.tables.records.ProjectKeywordsRecord

import kotlin.collections.Collection
import kotlin.collections.List

import org.jooq.Condition
import org.jooq.Field
import org.jooq.ForeignKey
import org.jooq.InverseForeignKey
import org.jooq.Name
import org.jooq.Path
import org.jooq.PlainSQL
import org.jooq.QueryPart
import org.jooq.Record
import org.jooq.SQL
import org.jooq.Schema
import org.jooq.Select
import org.jooq.Stringly
import org.jooq.Table
import org.jooq.TableField
import org.jooq.TableOptions
import org.jooq.UniqueKey
import org.jooq.impl.DSL
import org.jooq.impl.Internal
import org.jooq.impl.SQLDataType
import org.jooq.impl.TableImpl


/**
 * This class is generated by jOOQ.
 */
@Suppress("warnings")
open class ProjectKeywords(
    alias: Name,
    path: Table<out Record>?,
    childPath: ForeignKey<out Record, ProjectKeywordsRecord>?,
    parentPath: InverseForeignKey<out Record, ProjectKeywordsRecord>?,
    aliased: Table<ProjectKeywordsRecord>?,
    parameters: Array<Field<*>?>?,
    where: Condition?
): TableImpl<ProjectKeywordsRecord>(
    alias,
    Public.PUBLIC,
    path,
    childPath,
    parentPath,
    aliased,
    parameters,
    DSL.comment(""),
    TableOptions.table(),
    where,
) {
    companion object {

        /**
         * The reference instance of <code>public.project_keywords</code>
         */
        val PROJECT_KEYWORDS: ProjectKeywords = ProjectKeywords()
    }

    /**
     * The class holding records for this type
     */
    override fun getRecordType(): Class<ProjectKeywordsRecord> = ProjectKeywordsRecord::class.java

    /**
     * The column <code>public.project_keywords.id</code>.
     */
    val ID: TableField<ProjectKeywordsRecord, Int?> = createField(DSL.name("id"), SQLDataType.INTEGER.nullable(false), this, "")

    /**
     * The column <code>public.project_keywords.project_id</code>.
     */
    val PROJECT_ID: TableField<ProjectKeywordsRecord, String?> = createField(DSL.name("project_id"), SQLDataType.VARCHAR(255), this, "")

    /**
     * The column <code>public.project_keywords.keyword</code>.
     */
    val KEYWORD: TableField<ProjectKeywordsRecord, String?> = createField(DSL.name("keyword"), SQLDataType.VARCHAR(255), this, "")

    private constructor(alias: Name, aliased: Table<ProjectKeywordsRecord>?): this(alias, null, null, null, aliased, null, null)
    private constructor(alias: Name, aliased: Table<ProjectKeywordsRecord>?, parameters: Array<Field<*>?>?): this(alias, null, null, null, aliased, parameters, null)
    private constructor(alias: Name, aliased: Table<ProjectKeywordsRecord>?, where: Condition?): this(alias, null, null, null, aliased, null, where)

    /**
     * Create an aliased <code>public.project_keywords</code> table reference
     */
    constructor(alias: String): this(DSL.name(alias))

    /**
     * Create an aliased <code>public.project_keywords</code> table reference
     */
    constructor(alias: Name): this(alias, null)

    /**
     * Create a <code>public.project_keywords</code> table reference
     */
    constructor(): this(DSL.name("project_keywords"), null)

    constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProjectKeywordsRecord>?, parentPath: InverseForeignKey<out Record, ProjectKeywordsRecord>?): this(Internal.createPathAlias(path, childPath, parentPath), path, childPath, parentPath, PROJECT_KEYWORDS, null, null)

    /**
     * A subtype implementing {@link Path} for simplified path-based joins.
     */
    open class ProjectKeywordsPath : ProjectKeywords, Path<ProjectKeywordsRecord> {
        constructor(path: Table<out Record>, childPath: ForeignKey<out Record, ProjectKeywordsRecord>?, parentPath: InverseForeignKey<out Record, ProjectKeywordsRecord>?): super(path, childPath, parentPath)
        private constructor(alias: Name, aliased: Table<ProjectKeywordsRecord>): super(alias, aliased)
        override fun `as`(alias: String): ProjectKeywordsPath = ProjectKeywordsPath(DSL.name(alias), this)
        override fun `as`(alias: Name): ProjectKeywordsPath = ProjectKeywordsPath(alias, this)
        override fun `as`(alias: Table<*>): ProjectKeywordsPath = ProjectKeywordsPath(alias.qualifiedName, this)
    }
    override fun getSchema(): Schema? = if (aliased()) null else Public.PUBLIC
    override fun getPrimaryKey(): UniqueKey<ProjectKeywordsRecord> = PROJECT_KEYWORDS_PKEY
    override fun getReferences(): List<ForeignKey<ProjectKeywordsRecord, *>> = listOf(PROJECT_KEYWORDS__PROJECT_KEYWORDS_PROJECT_ID_FKEY)

    /**
     * Get the implicit join path to the <code>public.project</code> table.
     */
    fun project(): ProjectPath = project
    val project: ProjectPath by lazy { ProjectPath(this, PROJECT_KEYWORDS__PROJECT_KEYWORDS_PROJECT_ID_FKEY, null) }
    override fun `as`(alias: String): ProjectKeywords = ProjectKeywords(DSL.name(alias), this)
    override fun `as`(alias: Name): ProjectKeywords = ProjectKeywords(alias, this)
    override fun `as`(alias: Table<*>): ProjectKeywords = ProjectKeywords(alias.qualifiedName, this)

    /**
     * Rename this table
     */
    override fun rename(name: String): ProjectKeywords = ProjectKeywords(DSL.name(name), null)

    /**
     * Rename this table
     */
    override fun rename(name: Name): ProjectKeywords = ProjectKeywords(name, null)

    /**
     * Rename this table
     */
    override fun rename(name: Table<*>): ProjectKeywords = ProjectKeywords(name.qualifiedName, null)

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Condition?): ProjectKeywords = ProjectKeywords(qualifiedName, if (aliased()) this else null, condition)

    /**
     * Create an inline derived table from this table
     */
    override fun where(conditions: Collection<Condition>): ProjectKeywords = where(DSL.and(conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(vararg conditions: Condition?): ProjectKeywords = where(DSL.and(*conditions))

    /**
     * Create an inline derived table from this table
     */
    override fun where(condition: Field<Boolean?>?): ProjectKeywords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(condition: SQL): ProjectKeywords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String): ProjectKeywords = where(DSL.condition(condition))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg binds: Any?): ProjectKeywords = where(DSL.condition(condition, *binds))

    /**
     * Create an inline derived table from this table
     */
    @PlainSQL override fun where(@Stringly.SQL condition: String, vararg parts: QueryPart): ProjectKeywords = where(DSL.condition(condition, *parts))

    /**
     * Create an inline derived table from this table
     */
    override fun whereExists(select: Select<*>): ProjectKeywords = where(DSL.exists(select))

    /**
     * Create an inline derived table from this table
     */
    override fun whereNotExists(select: Select<*>): ProjectKeywords = where(DSL.notExists(select))
}
